// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// cart.js
export const CART_REMOVE_PRODUCT = 'CART_REMOVE_PRODUCT'
export const SAVE_PRODUCT = 'SAVE_PRODUCT'
export const SAVE_PRODUCTS = 'SAVE_PRODUCTS'
export const CART_PUSH_FIRST_PRODUCT = 'CART_PUSH_FIRST_PRODUCT'
export const CART_PUSH_NEW_PRODUCT = 'CART_PUSH_NEW_PRODUCT'
export const CART_INCREMENT_PRODUCT_QTY = 'CART_INCREMENT_PRODUCT_QTY'
export const CREATE_CHECKOUT_DATA = 'CREATE_CHECKOUT_DATA'
