query getSingleProduct($id: ID!) {
  product(id: $id, idType: SLUG) {
    id
    databaseId
    averageRating
    description
    name
    slug
    onSale
    productTags {
      nodes {
        name
        link
      }
    }
    image {
      altText
      uri
      title
      srcSet
      sourceUrl
      link
    }
    productCategories {
      nodes {
        name
        link
      }
    }
    galleryImages {
      nodes {
        altText
        uri
        link
        sourceUrl
      }
    }
    link
    ... on SimpleProduct {
      price
      id
    }
    ... on VariableProduct {
      price
      id
    }
    ... on ExternalProduct {
      price
      id
      contentType {
        node {
          id
        }
      }
    }
    ... on GroupProduct {
      products {
        nodes {
          ... on SimpleProduct {
            id
            price
          }
        }
      }
      id
    }
  }
}
