query getSingleProduct($id: ID!) {
  product(id: $id, idType: SLUG) {
    id
    databaseId
    averageRating
    description(format: RAW)
    name
    slug
    onSale
    productTags {
      nodes {
        name
        link
      }
    }
    image {
      altText
      uri
      title
      srcSet
      sourceUrl
      link
    }
    related(first: 3) {
      nodes {
        name
        slug
        link
        onSale
        image {
          altText
          uri
          title
          srcSet
          sourceUrl
          link
        }
        ... on VariableProduct {
          price
        }
        ... on ExternalProduct {
          price
        }
        ... on SimpleProduct {
          price
        }
        ... on GroupProduct {
          products {
            nodes {
              ... on SimpleProduct {
                price
              }
            }
          }
        }
      }
    }
    productCategories {
      nodes {
        name
        link
      }
    }
    galleryImages {
      nodes {
        altText
        uri
        link
        sourceUrl
      }
    }
    link
    ... on SimpleProduct {
      price
    }
    ... on VariableProduct {
      price
    }
    ... on ExternalProduct {
      price
    }
    ... on GroupProduct {
      products {
        nodes {
          ... on SimpleProduct {
            price
          }
        }
      }
    }
  }
}
